DEBUG = True

USERNAME = 'root'
PASSWORD = 'root'
SERVER = 'localhost:3306'
DB = 'flask_fundamentos'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "teste-chave"

BABEL_DEFAULT_LOCALE = 'pt'