"""empty message

Revision ID: 0f8b4f6cb0f0
Revises: cf21b1da4c51
Create Date: 2020-08-13 21:23:23.038819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8b4f6cb0f0'
down_revision = 'cf21b1da4c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('andre', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'andre')
    # ### end Alembic commands ###
